name: eyeCatch
description: "우리 아이 안심 모니터링 Eye Catch 플러터 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0                    # API 통신
  shared_preferences: ^2.2.2      # 토큰 저장
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.5+1
  # 💡 무거운 flutter_vlc_player 패키지 삭제 완료
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^10.0.0
  flutter_webrtc: ^1.4.1          # 새로운 실시간 P2P 통신용
  web_socket_channel: ^2.4.0      # 시그널링 웹소켓 통신용
  video_player: ^2.11.1
  #firebase_core: ^2.24.2
  #firebase_messaging: ^14.7.9
  #flutter_local_notifications: ^17.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/1babyscreen.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/eyeCatchicon.png"